services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: obscur_backend
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - obscur_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: obscur_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - obscur_network
networks:
  obscur_network:
    driver: bridge