services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: obscur_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    container_name: obscur_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend